
apiVersion: v1
kind: Service
metadata:
  name: healthai-backend
  labels:
    app: healthai-backend
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: healthai-backend
